//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace MapLinkChallenge.br.com.maplink.services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RouteSoap", Namespace="http://webservices.maplink2.com.br")]
    public partial class Route : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getRouteTotalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRouteTotalsBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRouteWithAlternativesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMultiRouteOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRouteOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRouteSummaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRouteDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRouteWithMapOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Route() {
            this.Url = global::MapLinkChallenge.Properties.Settings.Default.MapLinkChallenge_br_com_maplink_services_Route;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getRouteTotalsCompletedEventHandler getRouteTotalsCompleted;
        
        /// <remarks/>
        public event GetRouteTotalsBatchCompletedEventHandler GetRouteTotalsBatchCompleted;
        
        /// <remarks/>
        public event getRouteWithAlternativesCompletedEventHandler getRouteWithAlternativesCompleted;
        
        /// <remarks/>
        public event getMultiRouteCompletedEventHandler getMultiRouteCompleted;
        
        /// <remarks/>
        public event getRouteCompletedEventHandler getRouteCompleted;
        
        /// <remarks/>
        public event getRouteSummaryCompletedEventHandler getRouteSummaryCompleted;
        
        /// <remarks/>
        public event getRouteDescriptionCompletedEventHandler getRouteDescriptionCompleted;
        
        /// <remarks/>
        public event getRouteWithMapCompletedEventHandler getRouteWithMapCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRouteTotals", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RouteTotals getRouteTotals([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteOptions ro, string token) {
            object[] results = this.Invoke("getRouteTotals", new object[] {
                        rs,
                        ro,
                        token});
            return ((RouteTotals)(results[0]));
        }
        
        /// <remarks/>
        public void getRouteTotalsAsync(RouteStop[] rs, RouteOptions ro, string token) {
            this.getRouteTotalsAsync(rs, ro, token, null);
        }
        
        /// <remarks/>
        public void getRouteTotalsAsync(RouteStop[] rs, RouteOptions ro, string token, object userState) {
            if ((this.getRouteTotalsOperationCompleted == null)) {
                this.getRouteTotalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteTotalsOperationCompleted);
            }
            this.InvokeAsync("getRouteTotals", new object[] {
                        rs,
                        ro,
                        token}, this.getRouteTotalsOperationCompleted, userState);
        }
        
        private void OngetRouteTotalsOperationCompleted(object arg) {
            if ((this.getRouteTotalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteTotalsCompleted(this, new getRouteTotalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/GetRouteTotalsBatch", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteTotals[] GetRouteTotalsBatch([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteArray[] ra, RouteOptions ro, string token) {
            object[] results = this.Invoke("GetRouteTotalsBatch", new object[] {
                        ra,
                        ro,
                        token});
            return ((RouteTotals[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRouteTotalsBatchAsync(RouteArray[] ra, RouteOptions ro, string token) {
            this.GetRouteTotalsBatchAsync(ra, ro, token, null);
        }
        
        /// <remarks/>
        public void GetRouteTotalsBatchAsync(RouteArray[] ra, RouteOptions ro, string token, object userState) {
            if ((this.GetRouteTotalsBatchOperationCompleted == null)) {
                this.GetRouteTotalsBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRouteTotalsBatchOperationCompleted);
            }
            this.InvokeAsync("GetRouteTotalsBatch", new object[] {
                        ra,
                        ro,
                        token}, this.GetRouteTotalsBatchOperationCompleted, userState);
        }
        
        private void OnGetRouteTotalsBatchOperationCompleted(object arg) {
            if ((this.GetRouteTotalsBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRouteTotalsBatchCompleted(this, new GetRouteTotalsBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRouteWithAlternatives", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AlternativeRouteInfo getRouteWithAlternatives([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteOptions ro, string token) {
            object[] results = this.Invoke("getRouteWithAlternatives", new object[] {
                        rs,
                        ro,
                        token});
            return ((AlternativeRouteInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getRouteWithAlternativesAsync(RouteStop[] rs, RouteOptions ro, string token) {
            this.getRouteWithAlternativesAsync(rs, ro, token, null);
        }
        
        /// <remarks/>
        public void getRouteWithAlternativesAsync(RouteStop[] rs, RouteOptions ro, string token, object userState) {
            if ((this.getRouteWithAlternativesOperationCompleted == null)) {
                this.getRouteWithAlternativesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteWithAlternativesOperationCompleted);
            }
            this.InvokeAsync("getRouteWithAlternatives", new object[] {
                        rs,
                        ro,
                        token}, this.getRouteWithAlternativesOperationCompleted, userState);
        }
        
        private void OngetRouteWithAlternativesOperationCompleted(object arg) {
            if ((this.getRouteWithAlternativesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteWithAlternativesCompleted(this, new getRouteWithAlternativesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getMultiRoute", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MultiRoute getMultiRoute([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] MultiRouteRequest[] request, RouteOptions ro, string token) {
            object[] results = this.Invoke("getMultiRoute", new object[] {
                        request,
                        ro,
                        token});
            return ((MultiRoute)(results[0]));
        }
        
        /// <remarks/>
        public void getMultiRouteAsync(MultiRouteRequest[] request, RouteOptions ro, string token) {
            this.getMultiRouteAsync(request, ro, token, null);
        }
        
        /// <remarks/>
        public void getMultiRouteAsync(MultiRouteRequest[] request, RouteOptions ro, string token, object userState) {
            if ((this.getMultiRouteOperationCompleted == null)) {
                this.getMultiRouteOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMultiRouteOperationCompleted);
            }
            this.InvokeAsync("getMultiRoute", new object[] {
                        request,
                        ro,
                        token}, this.getMultiRouteOperationCompleted, userState);
        }
        
        private void OngetMultiRouteOperationCompleted(object arg) {
            if ((this.getMultiRouteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMultiRouteCompleted(this, new getMultiRouteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRoute", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RouteInfo getRoute([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteOptions ro, string token) {
            object[] results = this.Invoke("getRoute", new object[] {
                        rs,
                        ro,
                        token});
            return ((RouteInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getRouteAsync(RouteStop[] rs, RouteOptions ro, string token) {
            this.getRouteAsync(rs, ro, token, null);
        }
        
        /// <remarks/>
        public void getRouteAsync(RouteStop[] rs, RouteOptions ro, string token, object userState) {
            if ((this.getRouteOperationCompleted == null)) {
                this.getRouteOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteOperationCompleted);
            }
            this.InvokeAsync("getRoute", new object[] {
                        rs,
                        ro,
                        token}, this.getRouteOperationCompleted, userState);
        }
        
        private void OngetRouteOperationCompleted(object arg) {
            if ((this.getRouteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteCompleted(this, new getRouteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRouteSummary", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteSummary[] getRouteSummary([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteOptions ro, string token) {
            object[] results = this.Invoke("getRouteSummary", new object[] {
                        rs,
                        ro,
                        token});
            return ((RouteSummary[])(results[0]));
        }
        
        /// <remarks/>
        public void getRouteSummaryAsync(RouteStop[] rs, RouteOptions ro, string token) {
            this.getRouteSummaryAsync(rs, ro, token, null);
        }
        
        /// <remarks/>
        public void getRouteSummaryAsync(RouteStop[] rs, RouteOptions ro, string token, object userState) {
            if ((this.getRouteSummaryOperationCompleted == null)) {
                this.getRouteSummaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteSummaryOperationCompleted);
            }
            this.InvokeAsync("getRouteSummary", new object[] {
                        rs,
                        ro,
                        token}, this.getRouteSummaryOperationCompleted, userState);
        }
        
        private void OngetRouteSummaryOperationCompleted(object arg) {
            if ((this.getRouteSummaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteSummaryCompleted(this, new getRouteSummaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRouteDescription", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SegmentDescription[] getRouteDescription([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteOptions ro, string token) {
            object[] results = this.Invoke("getRouteDescription", new object[] {
                        rs,
                        ro,
                        token});
            return ((SegmentDescription[])(results[0]));
        }
        
        /// <remarks/>
        public void getRouteDescriptionAsync(RouteStop[] rs, RouteOptions ro, string token) {
            this.getRouteDescriptionAsync(rs, ro, token, null);
        }
        
        /// <remarks/>
        public void getRouteDescriptionAsync(RouteStop[] rs, RouteOptions ro, string token, object userState) {
            if ((this.getRouteDescriptionOperationCompleted == null)) {
                this.getRouteDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteDescriptionOperationCompleted);
            }
            this.InvokeAsync("getRouteDescription", new object[] {
                        rs,
                        ro,
                        token}, this.getRouteDescriptionOperationCompleted, userState);
        }
        
        private void OngetRouteDescriptionOperationCompleted(object arg) {
            if ((this.getRouteDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteDescriptionCompleted(this, new getRouteDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRouteWithMap", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RouteInfo getRouteWithMap([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteOptions ro, MapOptions mo, string token) {
            object[] results = this.Invoke("getRouteWithMap", new object[] {
                        rs,
                        ro,
                        mo,
                        token});
            return ((RouteInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getRouteWithMapAsync(RouteStop[] rs, RouteOptions ro, MapOptions mo, string token) {
            this.getRouteWithMapAsync(rs, ro, mo, token, null);
        }
        
        /// <remarks/>
        public void getRouteWithMapAsync(RouteStop[] rs, RouteOptions ro, MapOptions mo, string token, object userState) {
            if ((this.getRouteWithMapOperationCompleted == null)) {
                this.getRouteWithMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteWithMapOperationCompleted);
            }
            this.InvokeAsync("getRouteWithMap", new object[] {
                        rs,
                        ro,
                        mo,
                        token}, this.getRouteWithMapOperationCompleted, userState);
        }
        
        private void OngetRouteWithMapOperationCompleted(object arg) {
            if ((this.getRouteWithMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteWithMapCompleted(this, new getRouteWithMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteStop {
        
        private string descriptionField;
        
        private Point pointField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class Point {
        
        private double xField;
        
        private double yField;
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class MapSize {
        
        private int widthField;
        
        private int heightField;
        
        /// <remarks/>
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class MapOptions {
        
        private bool scaleBarField;
        
        private MapSize mapSizeField;
        
        /// <remarks/>
        public bool scaleBar {
            get {
                return this.scaleBarField;
            }
            set {
                this.scaleBarField = value;
            }
        }
        
        /// <remarks/>
        public MapSize mapSize {
            get {
                return this.mapSizeField;
            }
            set {
                this.mapSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class SingleRouteTotals {
        
        private RouteStop originField;
        
        private RouteStop destinField;
        
        private RouteTotals routeTotalsField;
        
        private string logRouteIdField;
        
        private MapInfo mapInfoField;
        
        /// <remarks/>
        public RouteStop origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public RouteStop destin {
            get {
                return this.destinField;
            }
            set {
                this.destinField = value;
            }
        }
        
        /// <remarks/>
        public RouteTotals routeTotals {
            get {
                return this.routeTotalsField;
            }
            set {
                this.routeTotalsField = value;
            }
        }
        
        /// <remarks/>
        public string logRouteId {
            get {
                return this.logRouteIdField;
            }
            set {
                this.logRouteIdField = value;
            }
        }
        
        /// <remarks/>
        public MapInfo mapInfo {
            get {
                return this.mapInfoField;
            }
            set {
                this.mapInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteTotals {
        
        private double totalDistanceField;
        
        private string totalTimeField;
        
        private double totalFuelUsedField;
        
        private double totaltollFeeCostField;
        
        private double totalfuelCostField;
        
        private double totalCostField;
        
        private double taxiFare1Field;
        
        private double taxiFare2Field;
        
        /// <remarks/>
        public double totalDistance {
            get {
                return this.totalDistanceField;
            }
            set {
                this.totalDistanceField = value;
            }
        }
        
        /// <remarks/>
        public string totalTime {
            get {
                return this.totalTimeField;
            }
            set {
                this.totalTimeField = value;
            }
        }
        
        /// <remarks/>
        public double totalFuelUsed {
            get {
                return this.totalFuelUsedField;
            }
            set {
                this.totalFuelUsedField = value;
            }
        }
        
        /// <remarks/>
        public double totaltollFeeCost {
            get {
                return this.totaltollFeeCostField;
            }
            set {
                this.totaltollFeeCostField = value;
            }
        }
        
        /// <remarks/>
        public double totalfuelCost {
            get {
                return this.totalfuelCostField;
            }
            set {
                this.totalfuelCostField = value;
            }
        }
        
        /// <remarks/>
        public double totalCost {
            get {
                return this.totalCostField;
            }
            set {
                this.totalCostField = value;
            }
        }
        
        /// <remarks/>
        public double taxiFare1 {
            get {
                return this.taxiFare1Field;
            }
            set {
                this.taxiFare1Field = value;
            }
        }
        
        /// <remarks/>
        public double taxiFare2 {
            get {
                return this.taxiFare2Field;
            }
            set {
                this.taxiFare2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class MapInfo {
        
        private string urlField;
        
        private Extent extentField;
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public Extent extent {
            get {
                return this.extentField;
            }
            set {
                this.extentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class Extent {
        
        private double xMinField;
        
        private double yMinField;
        
        private double xMaxField;
        
        private double yMaxField;
        
        /// <remarks/>
        public double XMin {
            get {
                return this.xMinField;
            }
            set {
                this.xMinField = value;
            }
        }
        
        /// <remarks/>
        public double YMin {
            get {
                return this.yMinField;
            }
            set {
                this.yMinField = value;
            }
        }
        
        /// <remarks/>
        public double XMax {
            get {
                return this.xMaxField;
            }
            set {
                this.xMaxField = value;
            }
        }
        
        /// <remarks/>
        public double YMax {
            get {
                return this.yMaxField;
            }
            set {
                this.yMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class MultiRoute {
        
        private SingleRouteTotals[] singleRouteTotalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SingleRouteTotals[] singleRouteTotals {
            get {
                return this.singleRouteTotalsField;
            }
            set {
                this.singleRouteTotalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class MultiRouteRequest {
        
        private RouteStop originField;
        
        private RouteStop destinationField;
        
        /// <remarks/>
        public RouteStop origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public RouteStop destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RoadType {
        
        private double twoLaneHighwayField;
        
        private double secondLaneUnderConstructionField;
        
        private double oneLaneRoadwayField;
        
        private double pavingWorkInProgressField;
        
        private double dirtRoadField;
        
        private double roadwayInPoorConditionsField;
        
        private double ferryField;
        
        /// <remarks/>
        public double twoLaneHighway {
            get {
                return this.twoLaneHighwayField;
            }
            set {
                this.twoLaneHighwayField = value;
            }
        }
        
        /// <remarks/>
        public double secondLaneUnderConstruction {
            get {
                return this.secondLaneUnderConstructionField;
            }
            set {
                this.secondLaneUnderConstructionField = value;
            }
        }
        
        /// <remarks/>
        public double oneLaneRoadway {
            get {
                return this.oneLaneRoadwayField;
            }
            set {
                this.oneLaneRoadwayField = value;
            }
        }
        
        /// <remarks/>
        public double pavingWorkInProgress {
            get {
                return this.pavingWorkInProgressField;
            }
            set {
                this.pavingWorkInProgressField = value;
            }
        }
        
        /// <remarks/>
        public double dirtRoad {
            get {
                return this.dirtRoadField;
            }
            set {
                this.dirtRoadField = value;
            }
        }
        
        /// <remarks/>
        public double roadwayInPoorConditions {
            get {
                return this.roadwayInPoorConditionsField;
            }
            set {
                this.roadwayInPoorConditionsField = value;
            }
        }
        
        /// <remarks/>
        public double ferry {
            get {
                return this.ferryField;
            }
            set {
                this.ferryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteSummary {
        
        private string descriptionField;
        
        private double distanceField;
        
        private Point pointField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class TollFeeDetails {
        
        private string nameField;
        
        private string directionField;
        
        private string addressField;
        
        private string concessionField;
        
        private string phoneField;
        
        private string stateField;
        
        private double priceField;
        
        private double pricePerAxleField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string concession {
            get {
                return this.concessionField;
            }
            set {
                this.concessionField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public double pricePerAxle {
            get {
                return this.pricePerAxleField;
            }
            set {
                this.pricePerAxleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class City {
        
        private string nameField;
        
        private string stateField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class POIDetails {
        
        private string clientIDField;
        
        private string nameField;
        
        private string addressInfoField;
        
        private string sourceField;
        
        private Point pointField;
        
        /// <remarks/>
        public string clientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string addressInfo {
            get {
                return this.addressInfoField;
            }
            set {
                this.addressInfoField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class SegmentDescription {
        
        private string commandField;
        
        private string descriptionField;
        
        private string poiRouteField;
        
        private POIDetails[] poiRouteDetailsField;
        
        private City cityField;
        
        private string tollFeeField;
        
        private TollFeeDetails tollFeeDetailsField;
        
        private string roadTypeField;
        
        private double distanceField;
        
        private double cumulativeDistanceField;
        
        private Point pointField;
        
        /// <remarks/>
        public string command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string poiRoute {
            get {
                return this.poiRouteField;
            }
            set {
                this.poiRouteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public POIDetails[] poiRouteDetails {
            get {
                return this.poiRouteDetailsField;
            }
            set {
                this.poiRouteDetailsField = value;
            }
        }
        
        /// <remarks/>
        public City city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string tollFee {
            get {
                return this.tollFeeField;
            }
            set {
                this.tollFeeField = value;
            }
        }
        
        /// <remarks/>
        public TollFeeDetails tollFeeDetails {
            get {
                return this.tollFeeDetailsField;
            }
            set {
                this.tollFeeDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string roadType {
            get {
                return this.roadTypeField;
            }
            set {
                this.roadTypeField = value;
            }
        }
        
        /// <remarks/>
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public double cumulativeDistance {
            get {
                return this.cumulativeDistanceField;
            }
            set {
                this.cumulativeDistanceField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteInfo {
        
        private string routeIdField;
        
        private MapInfo mapInfoField;
        
        private SegmentDescription[] segDescriptionField;
        
        private RouteTotals routeTotalsField;
        
        private RouteSummary[] routeSummaryField;
        
        private RoadType roadTypeField;
        
        /// <remarks/>
        public string routeId {
            get {
                return this.routeIdField;
            }
            set {
                this.routeIdField = value;
            }
        }
        
        /// <remarks/>
        public MapInfo MapInfo {
            get {
                return this.mapInfoField;
            }
            set {
                this.mapInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SegmentDescription[] segDescription {
            get {
                return this.segDescriptionField;
            }
            set {
                this.segDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public RouteTotals routeTotals {
            get {
                return this.routeTotalsField;
            }
            set {
                this.routeTotalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteSummary[] routeSummary {
            get {
                return this.routeSummaryField;
            }
            set {
                this.routeSummaryField = value;
            }
        }
        
        /// <remarks/>
        public RoadType roadType {
            get {
                return this.roadTypeField;
            }
            set {
                this.roadTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class AlternativeRouteInfo {
        
        private RouteInfo mainRouteField;
        
        private RouteInfo[] alternativesField;
        
        /// <remarks/>
        public RouteInfo mainRoute {
            get {
                return this.mainRouteField;
            }
            set {
                this.mainRouteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteInfo[] alternatives {
            get {
                return this.alternativesField;
            }
            set {
                this.alternativesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteArray {
        
        private RouteStop originField;
        
        private RouteStop destField;
        
        /// <remarks/>
        public RouteStop Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public RouteStop Dest {
            get {
                return this.destField;
            }
            set {
                this.destField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteLine {
        
        private int widthField;
        
        private string rGBField;
        
        private double transparencyField;
        
        /// <remarks/>
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public string RGB {
            get {
                return this.rGBField;
            }
            set {
                this.rGBField = value;
            }
        }
        
        /// <remarks/>
        public double transparency {
            get {
                return this.transparencyField;
            }
            set {
                this.transparencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class Vehicle {
        
        private int tankCapacityField;
        
        private float averageConsumptionField;
        
        private double fuelPriceField;
        
        private int averageSpeedField;
        
        private int tollFeeCatField;
        
        /// <remarks/>
        public int tankCapacity {
            get {
                return this.tankCapacityField;
            }
            set {
                this.tankCapacityField = value;
            }
        }
        
        /// <remarks/>
        public float averageConsumption {
            get {
                return this.averageConsumptionField;
            }
            set {
                this.averageConsumptionField = value;
            }
        }
        
        /// <remarks/>
        public double fuelPrice {
            get {
                return this.fuelPriceField;
            }
            set {
                this.fuelPriceField = value;
            }
        }
        
        /// <remarks/>
        public int averageSpeed {
            get {
                return this.averageSpeedField;
            }
            set {
                this.averageSpeedField = value;
            }
        }
        
        /// <remarks/>
        public int tollFeeCat {
            get {
                return this.tollFeeCatField;
            }
            set {
                this.tollFeeCatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteDetails {
        
        private int descriptionTypeField;
        
        private int routeTypeField;
        
        private bool optimizeRouteField;
        
        private string[] poiRouteField;
        
        private string[] barriersListField;
        
        private Point[] barrierPointsField;
        
        /// <remarks/>
        public int descriptionType {
            get {
                return this.descriptionTypeField;
            }
            set {
                this.descriptionTypeField = value;
            }
        }
        
        /// <remarks/>
        public int routeType {
            get {
                return this.routeTypeField;
            }
            set {
                this.routeTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool optimizeRoute {
            get {
                return this.optimizeRouteField;
            }
            set {
                this.optimizeRouteField = value;
            }
        }
        
        /// <remarks/>
        public string[] poiRoute {
            get {
                return this.poiRouteField;
            }
            set {
                this.poiRouteField = value;
            }
        }
        
        /// <remarks/>
        public string[] barriersList {
            get {
                return this.barriersListField;
            }
            set {
                this.barriersListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Point[] barrierPoints {
            get {
                return this.barrierPointsField;
            }
            set {
                this.barrierPointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteOptions {
        
        private string languageField;
        
        private RouteDetails routeDetailsField;
        
        private Vehicle vehicleField;
        
        private RouteLine[] routeLineField;
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public RouteDetails routeDetails {
            get {
                return this.routeDetailsField;
            }
            set {
                this.routeDetailsField = value;
            }
        }
        
        /// <remarks/>
        public Vehicle vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteLine[] routeLine {
            get {
                return this.routeLineField;
            }
            set {
                this.routeLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getRouteTotalsCompletedEventHandler(object sender, getRouteTotalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteTotalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteTotalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RouteTotals Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RouteTotals)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetRouteTotalsBatchCompletedEventHandler(object sender, GetRouteTotalsBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRouteTotalsBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRouteTotalsBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RouteTotals[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RouteTotals[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getRouteWithAlternativesCompletedEventHandler(object sender, getRouteWithAlternativesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteWithAlternativesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteWithAlternativesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AlternativeRouteInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AlternativeRouteInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getMultiRouteCompletedEventHandler(object sender, getMultiRouteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMultiRouteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMultiRouteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MultiRoute Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MultiRoute)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getRouteCompletedEventHandler(object sender, getRouteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RouteInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RouteInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getRouteSummaryCompletedEventHandler(object sender, getRouteSummaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RouteSummary[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RouteSummary[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getRouteDescriptionCompletedEventHandler(object sender, getRouteDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SegmentDescription[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SegmentDescription[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getRouteWithMapCompletedEventHandler(object sender, getRouteWithMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteWithMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteWithMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RouteInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RouteInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591